### ISSUE TITLE
ComponentMapper#reclaimPooled can throw OOBE

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#305]
```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 64 at com.artemis.utils.Bag.get(Bag.java:179) at com.artemis.ComponentManager.reclaimPooled(ComponentManager.java:99) at com.artemis.ComponentManager.create(ComponentManager.java:80) at com.artemis.ComponentManager.addComponents(ComponentManager.java:208) at com.artemis.World.createEntity(World.java:436) at net.mostlyoriginal.odb.archetype.ParticleImpl.create(ParticleImpl.java:112)
```

**Comment by DaanVanYperen** [comment]
Out Of Body Experience!

**Comment by Namek** [comment]
OOBE is too much. LD would be enough.

**Comment by junkdog** [comment]
Ludum dare?

**Comment by Namek** [comment]
Lucid Dreaming, heh.

**Comment by junkdog** [comment]
Fixed in https://github.com/junkdog/artemis-odb/commit/2b7db8849b1a8060619e71095e0ec1fc751bda2a
