### ISSUE TITLE
[BUG] NullPointerException at com.artemis.io.ArchetypeMapper.toClasses(ArchetypeMapper.java:46)

### ISSUE THREAD

**Issue by Mr00Anderson** [junkdog/artemis-odb#580]
I have been banging my head on the wall about this for two days. I have pinned the issue around Line 34 of ```ArchetypeMapper```

** Issue **
```
java.lang.NullPointerException
	at com.artemis.io.ArchetypeMapper.toClasses(ArchetypeMapper.java:46)
	at com.artemis.io.ArchetypeMapper.<init>(ArchetypeMapper.java:36)
	at com.artemis.io.JsonArtemisSerializer.save(JsonArtemisSerializer.java:68)
	at com.artemis.io.JsonArtemisSerializer.save(JsonArtemisSerializer.java:89)
	at com.artemis.managers.WorldSerializationManager.save(WorldSerializationManager.java:64)
	at com.virtual_hex.core.WorldSerializationTest.worldSerTest(WorldSerializationTest.java:58)
	... TRUNICATED ...
	at java.lang.Thread.run(Thread.java:748)
```

** Reproduce Steps **
 ```
public class TestComp extends Component {

    public TestComp() {
    }

    int testInt;
}
```
AND
```java
    public static void main(String[] args) {
        // Create the world
        WorldSerializationManager manager = new WorldSerializationManager();
        TagManager tagManager = new TagManager();

        World world = new World(
                new WorldConfiguration()
                        .setSystem(manager)
                        .setSystem(tagManager));

        JsonArtemisSerializer jsonArtemisSerializer = new JsonArtemisSerializer(world).prettyPrint(true);
		
        manager.setSerializer(jsonArtemisSerializer);

        ComponentMapper<TestComp> mapperTwo = new ComponentMapper<>(TestComp.class, world);

        // Create various simple and complex entities
        int simple1 = world.create();
        tagManager.register("TestTagSimple", simple1);

        TestComp testComp = mapperTwo.create(simple1);
        testComp.testInt = 10;

        world.process();

        EntitySubscription entitySubscription = world.getAspectSubscriptionManager().get(Aspect.all());
        IntBag entities = entitySubscription.getEntities();
        try(
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ){

            manager.save(bos, new SaveFileFormat(entities));
            String json = new String(bos.toByteArray());
            System.out.println(json);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**Comment by junkdog** [comment]
> ```java
>  ComponentMapper<TestComp> mapperTwo = new ComponentMapper<>(TestComp.class, world);
> ```

Hmm, I looks like an oversight on our end. Component mappers own own their component data, and artemis in turn assumes it owns/allocates all component mappers.
 
I _think_ this will work if you retrieve the mapper using `world.getMapper(TestComp.class)` instead of instantiating it yourself.

**Comment by DaanVanYperen** [comment]
@junkdog how would you like this fixed? Package local `ComponentMapper` constructor and something like `ComponentMapper.of(TestComp.class, world)` that delegates construction to `world.getMapper()`?

**Comment by Mr00Anderson** [comment]
I am not sure where

> > ```java
> >  ComponentMapper<TestComp> mapperTwo = new ComponentMapper<>(TestComp.class, world);
> > ```
> 
> Hmm, I looks like an oversight on our end. Component mappers own own their component data, and artemis in turn assumes it owns/allocates all component mappers.
> 
> I _think_ this will work if you retrieve the mapper using `world.getMapper(TestComp.class)` instead of instantiating it yourself.

I see. I used it externally for a test. There a few ways to access items.
