### ISSUE TITLE
[Question] Component construction/initialization with parameters

### ISSUE THREAD

**Issue by hoxu** [junkdog/artemis-odb#619]
I'm trying to use [Monix Vars](https://monix.io/api/current/monix/reactive/subjects/Var.html) in Components instead of plain variables. For testing I need to be able to provide a different Scheduler, thus I need constructor parameters.

Even though [EntityEdit.add](https://junkdog.github.io/javadoc/artemis-odb/2.2.0/com/artemis/EntityEdit.html#add-com.artemis.Component-) looks like it allows constructing a Component with non-empty constructor, EntityEdit.add [seems to first create the Component without constructor parameters before replacing it with the given Component](https://github.com/junkdog/artemis-odb/blob/be6a5c9b580ca4782d355f2b76de97543873adc9/artemis-core/artemis/src/main/java/com/artemis/EntityEdit.java#L74-L75). Moreover, the World constructor seems to choke on Components with no non-argument constructor:

```
com.artemis.InvalidComponentException: ExampleComponent: missing public constructor
	at com.artemis.ComponentTypeFactory.createComponentType(ComponentTypeFactory.java:65)
	at com.artemis.ComponentTypeFactory.getTypeFor(ComponentTypeFactory.java:54)
	at com.artemis.ComponentTypeFactory.getIndexFor(ComponentTypeFactory.java:100)
	at com.artemis.Aspect$Builder.associate(Aspect.java:359)
	at com.artemis.Aspect$Builder.build(Aspect.java:350)
	at com.artemis.EntitySubscription.<init>(EntitySubscription.java:32)
	at com.artemis.AspectSubscriptionManager.createSubscription(AspectSubscriptionManager.java:68)
	at com.artemis.AspectSubscriptionManager.get(AspectSubscriptionManager.java:64)
	at com.artemis.BaseEntitySystem.getSubscription(BaseEntitySystem.java:57)
	at com.artemis.BaseEntitySystem.setWorld(BaseEntitySystem.java:47)
	at com.artemis.WorldConfiguration.initialize(WorldConfiguration.java:171)
	at com.artemis.World.<init>(World.java:89)
```

Is there no way to use Components that require constructor parameters with artemis-odb?

**Comment by genaray** [comment]
Had the same issue... make sure you always have a public constructor without any params. Than it should work well :)

**Comment by DaanVanYperen** [comment]
Closing as answered.

**Comment by hoxu** [comment]
More like: component constructor parameters are not supported in artemis-odb.
